SELECT 
	CASE WHEN nmr.TEMPLATE_VERSION = '' THEN 'v1' ELSE nmr.TEMPLATE_VERSION END label,
	nmr.TEMPLATE_VERSION value
FROM 
	{stageDB}.SPARKPLUG_TEMPLATE_DEFINITION_REGISTRY nmr
WHERE 
	nmr.TEMPLATE_PATH = :dataModel
GROUP BY 
	nmr.TEMPLATE_VERSION
ORDER BY 
	nmr.TEMPLATE_VERSION