SELECT 
	nmr.GROUP_ID,
	nmr.EDGE_NODE_ID,
	nmr.DEVICE_ID,
	nmr.TEMPLATE_PATH
FROM 
	{stageDB}.SPARKPLUG_TEMPLATE_INSTANCE_REGISTRY nmr 
WHERE 
	nmr.TEMPLATE_REFERENCE = :dataModel AND 
	nmr.TEMPLATE_VERSION = :dataModelVersion
ORDER BY 
	nmr.GROUP_ID,
	nmr.EDGE_NODE_ID,
	nmr.DEVICE_ID,
	nmr.TEMPLATE_PATH