SELECT 
	COUNT(DISTINCT nmr.GROUP_ID) groupIds,
	COUNT(DISTINCT nmr.EDGE_NODE_ID) edgeNodeIds,
	COUNT(DISTINCT CONCAT(nmr.TEMPLATE_REFERENCE, nmr.TEMPLATE_VERSION)) udts,
	COUNT(*) udtInstances
FROM 
	{stageDB}.SPARKPLUG_TEMPLATE_INSTANCE_REGISTRY nmr